#!/usr/bin/env node
/**
 * Non-interactive TWA build for FoxiesDeck.
 *
 * Builds the Android project generated by init-twa.mjs and produces a signed
 * APK and signed App Bundle. Uses Gradle directly (the .bat/.sh wrapper) so it
 * works from Git Bash / MSYS2 on Windows, where `bubblewrap build` fails to
 * resolve `gradlew.bat`.
 */
import { execFileSync, spawn } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { patchGeneratedAndroidProject } from "./patch-generated-android.mjs";
import { prepareHybridMedia } from "./prepare-hybrid-android.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const PROJECT_DIR = path.resolve(
  process.env.TWA_PROJECT_DIR || path.join(ROOT, "com.foxiesdeck")
);
const PASSWORD_FILE = path.join(PROJECT_DIR, ".keystore-passwords");
const CONFIG_FILE = path.join(os.homedir(), ".bubblewrap", "config.json");

const knownLicenseHashes = {
  "android-sdk-license": "24333f8a63b6825ea9c5514f83c2829b004d1fee",
  "android-sdk-preview-license":
    "84831b9409646a918e30573bab4c9c91346d8abd",
  "android-googletv-license": "601085b94cd77f0b54ff86406957099ebe79c4d6",
  "android-sdk-arm-dbt-license":
    "859f317696f67ef3d7f30a50a5560e7834b43903",
};

function fileExists(p) {
  try {
    fs.accessSync(p);
    return true;
  } catch {
    return false;
  }
}

function readJson(p) {
  return JSON.parse(fs.readFileSync(p, "utf8"));
}

function latestBuildTools(androidSdkPath) {
  const btDir = path.join(androidSdkPath, "build-tools");
  if (!fileExists(btDir)) return null;
  const versions = fs
    .readdirSync(btDir)
    .filter((d) => fileExists(path.join(btDir, d, "zipalign.exe")))
    .sort((a, b) => {
      const parse = (s) => s.split(".").map((n) => parseInt(n, 10) || 0);
      const pa = parse(a);
      const pb = parse(b);
      for (let i = 0; i < Math.max(pa.length, pb.length); i++) {
        const diff = (pa[i] || 0) - (pb[i] || 0);
        if (diff !== 0) return diff;
      }
      return 0;
    });
  return versions.length ? path.join(btDir, versions[versions.length - 1]) : null;
}

function ensureLicenses(androidSdkPath) {
  const licensesDir = path.join(androidSdkPath, "licenses");
  if (!fileExists(licensesDir)) fs.mkdirSync(licensesDir, { recursive: true });
  for (const [name, hash] of Object.entries(knownLicenseHashes)) {
    const licenseFile = path.join(licensesDir, name);
    if (!fileExists(licenseFile)) {
      fs.writeFileSync(licenseFile, hash + "\n");
    }
  }
}

function quoteArg(arg) {
  if (arg.includes(" ") || arg.includes("&") || arg.includes("|")) {
    return `"${arg}"`;
  }
  return arg;
}

function run(cmd, args, options = {}) {
  return new Promise((resolve, reject) => {
    const isWin = process.platform === "win32";
    let spawnCmd = cmd;
    let spawnArgs = args;
    let shell = false;

    if (cmd === "./gradlew" && isWin) {
      // Node on Windows cannot resolve a relative batch file, so use cmd /c.
      spawnCmd = "cmd";
      spawnArgs = ["/c", `.\\gradlew.bat ${args.map(quoteArg).join(" ")}`];
    } else if (isWin && (cmd.endsWith(".bat") || cmd.endsWith(".cmd"))) {
      spawnCmd = "cmd";
      spawnArgs = ["/c", `${cmd} ${args.map(quoteArg).join(" ")}`];
    }

    const child = spawn(spawnCmd, spawnArgs, {
      cwd: options.cwd || PROJECT_DIR,
      env: options.env || process.env,
      stdio: options.stdio || "inherit",
      shell,
    });
    child.on("error", reject);
    child.on("close", (code) => {
      if (code === 0) resolve();
      else
        reject(
          new Error(`Command failed with code ${code}: ${cmd} ${args.join(" ")}`)
        );
    });
  });
}

function findBundletoolJar() {
  const candidates = [
    process.env.BUNDLETOOL_JAR,
    path.join(ROOT, "bundletool-all-1.18.3.jar"),
    path.join(os.tmpdir(), "bundletool-all-1.18.3.jar"),
  ].filter(Boolean);

  const resolved = candidates
    .map((candidate) => path.resolve(candidate))
    .find((candidate) => fileExists(candidate));

  if (!resolved) {
    throw new Error(
      "bundletool-all-1.18.3.jar is required to produce the full-media universal APK. " +
        "Set BUNDLETOOL_JAR to its path or place it in the system temp directory."
    );
  }
  return resolved;
}

async function buildUniversalApk({
  jdkPath,
  bundletoolJar,
  signedAab,
  targetApk,
  keystorePath,
  keystoreAlias,
  keystorePassword,
  keyPassword,
  env,
}) {
  const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "foxiesdeck-universal-"));
  const apksPath = path.join(tempDir, "universal.apks");
  const extractDir = path.join(tempDir, "extract");
  fs.mkdirSync(extractDir, { recursive: true });

  const javaExecutable = path.join(
    jdkPath,
    "bin",
    process.platform === "win32" ? "java.exe" : "java",
  );
  const jarExecutable = path.join(
    jdkPath,
    "bin",
    process.platform === "win32" ? "jar.exe" : "jar",
  );

  try {
    console.log("Building full-media universal APK...");
    await run(javaExecutable, [
      "-jar",
      bundletoolJar,
      "build-apks",
      `--bundle=${signedAab}`,
      `--output=${apksPath}`,
      "--mode=universal",
      `--ks=${keystorePath}`,
      `--ks-key-alias=${keystoreAlias}`,
      `--ks-pass=pass:${keystorePassword}`,
      `--key-pass=pass:${keyPassword}`,
      "--overwrite",
    ], { env });

    await run(jarExecutable, ["xf", apksPath, "universal.apk"], {
      cwd: extractDir,
      env,
    });

    const universalPath = path.join(extractDir, "universal.apk");
    if (!fileExists(universalPath)) {
      throw new Error("bundletool did not produce universal.apk.");
    }
    fs.copyFileSync(universalPath, targetApk);
  } finally {
    fs.rmSync(tempDir, { recursive: true, force: true });
  }
}

async function validateReleaseArtifacts({
  javaExecutable,
  buildTools,
  bundletoolJar,
  signedAab,
  signedApk,
  env,
}) {
  console.log("Validating signed release artifacts...");
  await run(
    javaExecutable,
    ["-jar", bundletoolJar, "validate", `--bundle=${signedAab}`],
    { env, stdio: ["ignore", "ignore", "inherit"] },
  );
  await run(
    path.join(buildTools, "apksigner.bat"),
    ["verify", signedApk],
    { env, stdio: ["ignore", "ignore", "inherit"] },
  );
  console.log("Release artifact validation passed.");
}

export function validateAssetPack({ jarExecutable, signedAab, indexPath, env }) {
  const index = readJson(indexPath);
  const expected = new Set(
    index.assets.map(({ relativePath }) => `ui_media/assets/${relativePath}`),
  );
  const listing = execFileSync(jarExecutable, ["tf", signedAab], {
    cwd: PROJECT_DIR,
    env,
    encoding: "utf8",
  });
  const actual = new Set(
    listing
      .split(/\r?\n/)
      .map((entry) => entry.trim())
      .filter((entry) => entry.startsWith("ui_media/assets/")),
  );
  const missing = [...expected].filter((entry) => !actual.has(entry));
  const unexpected = [...actual].filter((entry) => !expected.has(entry));

  if (missing.length > 0 || unexpected.length > 0 || actual.size !== expected.size) {
    throw new Error(
      `AAB media pack mismatch: expected ${expected.size} assets, found ${actual.size}; ` +
        `missing=${missing.length}, unexpected=${unexpected.length}`,
    );
  }

  console.log(`Media pack validation passed: ${actual.size} indexed assets are in ui_media.`);
}

async function main() {
  if (!fileExists(PASSWORD_FILE)) {
    throw new Error(
      `Keystore passwords not found at ${PASSWORD_FILE}. Run \`npm run pwa:init\` first.`
    );
  }

  const config = fileExists(CONFIG_FILE) ? readJson(CONFIG_FILE) : {};
  const androidSdkPath =
    process.env.ANDROID_HOME ||
    process.env.ANDROID_SDK_ROOT ||
    config.androidSdkPath;
  const jdkPath = process.env.JDK_PATH || config.jdkPath;

  if (!androidSdkPath) {
    throw new Error(
      "Android SDK path not found. Set ANDROID_HOME or run Bubblewrap init once."
    );
  }
  if (!jdkPath) {
    throw new Error("JDK path not found. Set JDK_PATH or run Bubblewrap init once.");
  }

  ensureLicenses(androidSdkPath);

  const env = {
    ...process.env,
    ANDROID_HOME: androidSdkPath,
    ANDROID_SDK_ROOT: androidSdkPath,
  };

  const buildTools = latestBuildTools(androidSdkPath);
  if (!buildTools) {
    throw new Error(
      "Android Build Tools not found. Install them with:\n" +
        `  sdkmanager "build-tools;36.0.0"`
    );
  }

  let keystorePassword = process.env.TWA_KEYSTORE_PASSWORD;
  let keyPassword = process.env.TWA_KEY_PASSWORD || keystorePassword;

  if (!keystorePassword && fileExists(PASSWORD_FILE)) {
    const passwords = readJson(PASSWORD_FILE);
    keystorePassword = passwords.keystorePassword;
    keyPassword = passwords.keyPassword;
  }

  if (!keystorePassword) {
    throw new Error(
      "Keystore password not found. Set TWA_KEYSTORE_PASSWORD or create " +
        `${PASSWORD_FILE} by running \`npm run pwa:init\`.`
    );
  }

  if (!keyPassword) {
    throw new Error(
      "Key password not found. Set TWA_KEY_PASSWORD or create " +
        `${PASSWORD_FILE} by running \`npm run pwa:init\`.`
    );
  }

  const manifest = readJson(path.join(PROJECT_DIR, "twa-manifest.json"));
  const generatedProject = await patchGeneratedAndroidProject(PROJECT_DIR);
  if (
    String(manifest.packageId) !== generatedProject.packageName ||
    String(manifest.host) !== generatedProject.host
  ) {
    throw new Error(
      "Android identity metadata is inconsistent. Update twa-manifest.json " +
        `(${manifest.packageId}/${manifest.host}) or the generated Gradle project ` +
        `(${generatedProject.packageName}/${generatedProject.host}) before building.`,
    );
  }
  if (
    Number(manifest.appVersionCode) !== generatedProject.versionCode ||
    String(manifest.appVersionName) !== generatedProject.versionName
  ) {
    throw new Error(
      "Android version metadata is inconsistent. Update twa-manifest.json " +
        `(${manifest.appVersionName}/${manifest.appVersionCode}) or the generated Gradle project ` +
      `(${generatedProject.versionName}/${generatedProject.versionCode}) before building.`,
    );
  }

  // Always create a fresh web build before indexing media. Otherwise an
  // otherwise successful Android build could silently package an older .next
  // output than the source currently checked out.
  console.log("Building the Next.js website...");
  await run(
    process.platform === "win32" ? "npm.cmd" : "npm",
    ["run", "build"],
    { cwd: ROOT, env: process.env },
  );
  await prepareHybridMedia(PROJECT_DIR);
  const keystorePath = manifest.signingKey.path;
  const keystoreAlias = manifest.signingKey.alias;
  const bundletoolJar = findBundletoolJar();

  const gradlew = process.platform === "win32" ? "./gradlew" : "./gradlew";

  console.log("Building APK...");
  await run(gradlew, ["assembleRelease", "--stacktrace"], { env });

  const unsignedApk = "app/build/outputs/apk/release/app-release-unsigned.apk";
  const alignedApk = "app-release-unsigned-aligned.apk";
  const baseSignedApk = "app-release-base-signed.apk";
  const signedApk = "app-release-signed.apk";
  const unsignedAab = "app/build/outputs/bundle/release/app-release.aab";
  const signedAab = "app-release-bundle.aab";

  for (const f of [alignedApk, baseSignedApk, signedApk, signedAab]) {
    if (fileExists(path.join(PROJECT_DIR, f))) fs.unlinkSync(path.join(PROJECT_DIR, f));
  }

  console.log("Aligning APK...");
  await run(path.join(buildTools, "zipalign.exe"), [
    "-v",
    "-f",
    "4",
    unsignedApk,
    alignedApk,
  ], { env });

  console.log("Signing APK...");
  await run(path.join(buildTools, "apksigner.bat"), [
    "sign",
    "--ks",
    keystorePath,
    "--ks-key-alias",
    keystoreAlias,
    `--ks-pass=pass:${keystorePassword}`,
    `--key-pass=pass:${keyPassword}`,
    "--out",
    baseSignedApk,
    alignedApk,
  ], { env });

  console.log("Building App Bundle...");
  await run(gradlew, ["bundleRelease", "--stacktrace"], { env });

  console.log("Signing App Bundle...");
  await run(path.join(jdkPath, "bin", "jarsigner.exe"), [
    "-verbose",
    "-sigalg",
    "SHA256withRSA",
    "-digestalg",
    "SHA-256",
    "-keystore",
    keystorePath,
    "-storepass",
    keystorePassword,
    "-keypass",
    keyPassword,
    unsignedAab,
    keystoreAlias,
  ], { env });

  fs.copyFileSync(path.join(PROJECT_DIR, unsignedAab), path.join(PROJECT_DIR, signedAab));

  await buildUniversalApk({
    jdkPath,
    bundletoolJar,
    signedAab: path.join(PROJECT_DIR, signedAab),
    targetApk: path.join(PROJECT_DIR, signedApk),
    keystorePath,
    keystoreAlias,
    keystorePassword,
    keyPassword,
    env,
  });

  await validateReleaseArtifacts({
    javaExecutable: path.join(
      jdkPath,
      "bin",
      process.platform === "win32" ? "java.exe" : "java",
    ),
    buildTools,
    bundletoolJar,
    signedAab: path.join(PROJECT_DIR, signedAab),
    signedApk: path.join(PROJECT_DIR, signedApk),
    env,
  });

  validateAssetPack({
    jarExecutable: path.join(
      jdkPath,
      "bin",
      process.platform === "win32" ? "jar.exe" : "jar",
    ),
    signedAab: path.join(PROJECT_DIR, signedAab),
    indexPath: path.join(PROJECT_DIR, "app", "src", "main", "assets", "ui-media-index.json"),
    env,
  });

  console.log("\n✅ Build complete.");
  console.log(`Signed APK:  ${path.join(PROJECT_DIR, signedApk)} (universal, includes install-time media)`);
  console.log(`Base APK:    ${path.join(PROJECT_DIR, baseSignedApk)} (shell only)`);
  console.log(`Signed AAB:  ${path.join(PROJECT_DIR, signedAab)}`);
  console.log("The website distributes the app through Google Play; the APK remains a local release artifact.");
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
