#!/usr/bin/env node
/**
 * Non-interactive TWA build for FoxiesDeck.
 *
 * Builds the Android project generated by init-twa.mjs and produces a signed
 * APK and signed App Bundle. Uses Gradle directly (the .bat/.sh wrapper) so it
 * works from Git Bash / MSYS2 on Windows, where `bubblewrap build` fails to
 * resolve `gradlew.bat`.
 */
import { spawn } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const PROJECT_DIR = path.resolve(
  process.env.TWA_PROJECT_DIR || path.join(ROOT, "com.foxiesdeck")
);
const PASSWORD_FILE = path.join(PROJECT_DIR, ".keystore-passwords");
const CONFIG_FILE = path.join(os.homedir(), ".bubblewrap", "config.json");

const knownLicenseHashes = {
  "android-sdk-license": "24333f8a63b6825ea9c5514f83c2829b004d1fee",
  "android-sdk-preview-license":
    "84831b9409646a918e30573bab4c9c91346d8abd",
  "android-googletv-license": "601085b94cd77f0b54ff86406957099ebe79c4d6",
  "android-sdk-arm-dbt-license":
    "859f317696f67ef3d7f30a50a5560e7834b43903",
};

function fileExists(p) {
  try {
    fs.accessSync(p);
    return true;
  } catch {
    return false;
  }
}

function readJson(p) {
  return JSON.parse(fs.readFileSync(p, "utf8"));
}

function latestBuildTools(androidSdkPath) {
  const btDir = path.join(androidSdkPath, "build-tools");
  if (!fileExists(btDir)) return null;
  const versions = fs
    .readdirSync(btDir)
    .filter((d) => fileExists(path.join(btDir, d, "zipalign.exe")))
    .sort((a, b) => {
      const parse = (s) => s.split(".").map((n) => parseInt(n, 10) || 0);
      const pa = parse(a);
      const pb = parse(b);
      for (let i = 0; i < Math.max(pa.length, pb.length); i++) {
        const diff = (pa[i] || 0) - (pb[i] || 0);
        if (diff !== 0) return diff;
      }
      return 0;
    });
  return versions.length ? path.join(btDir, versions[versions.length - 1]) : null;
}

function ensureLicenses(androidSdkPath) {
  const licensesDir = path.join(androidSdkPath, "licenses");
  if (!fileExists(licensesDir)) fs.mkdirSync(licensesDir, { recursive: true });
  for (const [name, hash] of Object.entries(knownLicenseHashes)) {
    const licenseFile = path.join(licensesDir, name);
    if (!fileExists(licenseFile)) {
      fs.writeFileSync(licenseFile, hash + "\n");
    }
  }
}

function quoteArg(arg) {
  if (arg.includes(" ") || arg.includes("&") || arg.includes("|")) {
    return `"${arg}"`;
  }
  return arg;
}

function run(cmd, args, options = {}) {
  return new Promise((resolve, reject) => {
    const isWin = process.platform === "win32";
    let spawnCmd = cmd;
    let spawnArgs = args;
    let shell = false;

    if (cmd === "./gradlew" && isWin) {
      // Node on Windows cannot resolve a relative batch file, so use cmd /c.
      spawnCmd = "cmd";
      spawnArgs = ["/c", `.\\gradlew.bat ${args.map(quoteArg).join(" ")}`];
    } else if (isWin && (cmd.endsWith(".bat") || cmd.endsWith(".cmd"))) {
      spawnCmd = "cmd";
      spawnArgs = ["/c", `${cmd} ${args.map(quoteArg).join(" ")}`];
    }

    const child = spawn(spawnCmd, spawnArgs, {
      cwd: options.cwd || PROJECT_DIR,
      env: options.env || process.env,
      stdio: options.stdio || "inherit",
      shell,
    });
    child.on("error", reject);
    child.on("close", (code) => {
      if (code === 0) resolve();
      else
        reject(
          new Error(`Command failed with code ${code}: ${cmd} ${args.join(" ")}`)
        );
    });
  });
}

async function main() {
  if (!fileExists(PASSWORD_FILE)) {
    throw new Error(
      `Keystore passwords not found at ${PASSWORD_FILE}. Run \`npm run pwa:init\` first.`
    );
  }

  const config = fileExists(CONFIG_FILE) ? readJson(CONFIG_FILE) : {};
  const androidSdkPath =
    process.env.ANDROID_HOME ||
    process.env.ANDROID_SDK_ROOT ||
    config.androidSdkPath;
  const jdkPath = process.env.JDK_PATH || config.jdkPath;

  if (!androidSdkPath) {
    throw new Error(
      "Android SDK path not found. Set ANDROID_HOME or run Bubblewrap init once."
    );
  }
  if (!jdkPath) {
    throw new Error("JDK path not found. Set JDK_PATH or run Bubblewrap init once.");
  }

  ensureLicenses(androidSdkPath);

  const env = {
    ...process.env,
    ANDROID_HOME: androidSdkPath,
    ANDROID_SDK_ROOT: androidSdkPath,
  };

  const buildTools = latestBuildTools(androidSdkPath);
  if (!buildTools) {
    throw new Error(
      "Android Build Tools not found. Install them with:\n" +
        `  sdkmanager "build-tools;35.0.0"`
    );
  }

  const passwords = readJson(PASSWORD_FILE);
  const keystorePassword = passwords.keystorePassword;
  const keyPassword = passwords.keyPassword;

  const manifest = readJson(path.join(PROJECT_DIR, "twa-manifest.json"));
  const keystorePath = manifest.signingKey.path;
  const keystoreAlias = manifest.signingKey.alias;

  const gradlew = process.platform === "win32" ? "./gradlew" : "./gradlew";

  console.log("Building APK...");
  await run(gradlew, ["assembleRelease", "--stacktrace"], { env });

  const unsignedApk = "app/build/outputs/apk/release/app-release-unsigned.apk";
  const alignedApk = "app-release-unsigned-aligned.apk";
  const signedApk = "app-release-signed.apk";
  const unsignedAab = "app/build/outputs/bundle/release/app-release.aab";
  const signedAab = "app-release-bundle.aab";

  for (const f of [alignedApk, signedApk, signedAab]) {
    if (fileExists(path.join(PROJECT_DIR, f))) fs.unlinkSync(path.join(PROJECT_DIR, f));
  }

  console.log("Aligning APK...");
  await run(path.join(buildTools, "zipalign.exe"), [
    "-v",
    "-f",
    "4",
    unsignedApk,
    alignedApk,
  ], { env });

  console.log("Signing APK...");
  await run(path.join(buildTools, "apksigner.bat"), [
    "sign",
    "--ks",
    keystorePath,
    "--ks-key-alias",
    keystoreAlias,
    `--ks-pass=pass:${keystorePassword}`,
    `--key-pass=pass:${keyPassword}`,
    "--out",
    signedApk,
    alignedApk,
  ], { env });

  console.log("Building App Bundle...");
  await run(gradlew, ["bundleRelease", "--stacktrace"], { env });

  console.log("Signing App Bundle...");
  await run(path.join(jdkPath, "bin", "jarsigner.exe"), [
    "-verbose",
    "-sigalg",
    "SHA256withRSA",
    "-digestalg",
    "SHA-256",
    "-keystore",
    keystorePath,
    "-storepass",
    keystorePassword,
    "-keypass",
    keyPassword,
    unsignedAab,
    keystoreAlias,
  ], { env });

  fs.copyFileSync(path.join(PROJECT_DIR, unsignedAab), path.join(PROJECT_DIR, signedAab));

  const publicDownloadDir = path.join(ROOT, "public", "download");
  if (!fileExists(publicDownloadDir)) fs.mkdirSync(publicDownloadDir, { recursive: true });
  fs.copyFileSync(
    path.join(PROJECT_DIR, signedApk),
    path.join(publicDownloadDir, "app-release-signed.apk")
  );

  console.log("\n✅ Build complete.");
  console.log(`Signed APK:  ${path.join(PROJECT_DIR, signedApk)}`);
  console.log(`Signed AAB:  ${path.join(PROJECT_DIR, signedAab)}`);
  console.log(`Public download: ${path.join(publicDownloadDir, "app-release-signed.apk")}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
