create extension if not exists pgcrypto;

-- Keep the account directory private. The Social Studio API returns only the
-- non-email fields required by the authenticated admin workspace.
create table if not exists public.social_medias (
  id bigint generated by default as identity primary key,
  "Social Media" text not null,
  "Account Name" text not null,
  description text
);

alter table public.social_medias enable row level security;
revoke all on table public.social_medias from anon, authenticated;
grant select, insert, update, delete on table public.social_medias to service_role;

create table public.social_media_connections (
  id uuid primary key default gen_random_uuid(),
  social_media_id bigint not null unique references public.social_medias(id) on delete restrict,
  provider text not null check (provider in ('x', 'meta', 'tiktok', 'youtube', 'pinterest')),
  provider_account_id text,
  encrypted_access_token text,
  encrypted_refresh_token text,
  token_expires_at timestamptz,
  granted_scopes text[] not null default '{}',
  status text not null default 'disconnected' check (status in ('disconnected', 'connected', 'expired', 'revoked', 'error')),
  last_error_code text,
  last_error_message text,
  connected_at timestamptz,
  disconnected_at timestamptz,
  last_validated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (
    status <> 'connected'
    or (provider_account_id is not null and encrypted_access_token is not null)
  )
);

create index social_media_connections_provider_status_idx
  on public.social_media_connections(provider, status);

create table public.social_automation_executions (
  id uuid primary key default gen_random_uuid(),
  owner_key text not null,
  automation_group_id uuid not null,
  automation_row_id uuid not null,
  idempotency_key text not null unique,
  resolved_content_type text not null check (resolved_content_type in ('text', 'image', 'video')),
  resolved_generator text not null,
  resolved_language_code text not null,
  resolved_native_language_code text not null,
  resolved_tier text not null check (resolved_tier in ('A1', 'A2', 'B1', 'B2', 'C1')),
  source_snapshot jsonb not null default '{}'::jsonb check (jsonb_typeof(source_snapshot) = 'object'),
  scheduled_for timestamptz not null,
  claimed_at timestamptz,
  completed_at timestamptz,
  status text not null default 'scheduled' check (status in ('scheduled', 'queued', 'running', 'succeeded', 'failed', 'cancelled')),
  attempt_count integer not null default 0 check (attempt_count >= 0),
  next_attempt_at timestamptz,
  last_error_code text,
  last_error_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index social_automation_executions_due_idx
  on public.social_automation_executions(status, scheduled_for, next_attempt_at);
create index social_automation_executions_row_created_idx
  on public.social_automation_executions(automation_row_id, created_at desc);

create table public.social_content_generation_jobs (
  id uuid primary key default gen_random_uuid(),
  execution_id uuid not null unique references public.social_automation_executions(id) on delete cascade,
  provider text,
  status text not null default 'queued' check (status in ('queued', 'running', 'succeeded', 'failed', 'cancelled')),
  attempt_count integer not null default 0 check (attempt_count >= 0),
  request_payload jsonb not null default '{}'::jsonb check (jsonb_typeof(request_payload) = 'object'),
  result_payload jsonb not null default '{}'::jsonb check (jsonb_typeof(result_payload) = 'object'),
  started_at timestamptz,
  completed_at timestamptz,
  last_error_code text,
  last_error_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index social_content_generation_jobs_status_idx
  on public.social_content_generation_jobs(status, created_at);

create table public.social_automation_assets (
  id uuid primary key default gen_random_uuid(),
  execution_id uuid not null references public.social_automation_executions(id) on delete cascade,
  generation_job_id uuid references public.social_content_generation_jobs(id) on delete set null,
  asset_type text not null check (asset_type in ('text', 'image', 'video', 'audio')),
  storage_bucket text,
  storage_path text,
  mime_type text,
  caption text,
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata) = 'object'),
  created_at timestamptz not null default now(),
  unique nulls not distinct (storage_bucket, storage_path)
);

create index social_automation_assets_execution_idx
  on public.social_automation_assets(execution_id, created_at);

create table public.social_publish_delivery_jobs (
  id uuid primary key default gen_random_uuid(),
  execution_id uuid not null references public.social_automation_executions(id) on delete cascade,
  connection_id uuid not null references public.social_media_connections(id) on delete restrict,
  social_media_id bigint not null references public.social_medias(id) on delete restrict,
  asset_id uuid references public.social_automation_assets(id) on delete set null,
  provider text not null check (provider in ('x', 'meta', 'tiktok', 'youtube', 'pinterest')),
  status text not null default 'queued' check (status in ('queued', 'running', 'succeeded', 'failed', 'cancelled')),
  attempt_count integer not null default 0 check (attempt_count >= 0),
  scheduled_for timestamptz not null,
  published_at timestamptz,
  provider_post_id text,
  provider_post_url text,
  last_error_code text,
  last_error_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (execution_id, social_media_id)
);

create index social_publish_delivery_jobs_due_idx
  on public.social_publish_delivery_jobs(status, scheduled_for);
create index social_publish_delivery_jobs_connection_idx
  on public.social_publish_delivery_jobs(connection_id, status);

create table public.social_automation_audit_logs (
  id uuid primary key default gen_random_uuid(),
  execution_id uuid references public.social_automation_executions(id) on delete cascade,
  delivery_job_id uuid references public.social_publish_delivery_jobs(id) on delete cascade,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb check (jsonb_typeof(payload) = 'object'),
  created_at timestamptz not null default now()
);

create index social_automation_audit_logs_execution_idx
  on public.social_automation_audit_logs(execution_id, created_at desc);
create index social_automation_audit_logs_delivery_idx
  on public.social_automation_audit_logs(delivery_job_id, created_at desc);

alter table public.social_media_connections enable row level security;
alter table public.social_automation_executions enable row level security;
alter table public.social_content_generation_jobs enable row level security;
alter table public.social_automation_assets enable row level security;
alter table public.social_publish_delivery_jobs enable row level security;
alter table public.social_automation_audit_logs enable row level security;

revoke all on table public.social_media_connections from anon, authenticated;
revoke all on table public.social_automation_executions from anon, authenticated;
revoke all on table public.social_content_generation_jobs from anon, authenticated;
revoke all on table public.social_automation_assets from anon, authenticated;
revoke all on table public.social_publish_delivery_jobs from anon, authenticated;
revoke all on table public.social_automation_audit_logs from anon, authenticated;

grant select, insert, update, delete on table public.social_media_connections to service_role;
grant select, insert, update, delete on table public.social_automation_executions to service_role;
grant select, insert, update, delete on table public.social_content_generation_jobs to service_role;
grant select, insert, update, delete on table public.social_automation_assets to service_role;
grant select, insert, update, delete on table public.social_publish_delivery_jobs to service_role;
grant select, insert, update, delete on table public.social_automation_audit_logs to service_role;
