// Generated by scripts/generate-card-definitions-batch.mjs.
// This stays empty until the first completed Batch output is applied; quiz code
// intentionally falls back to the existing learning question while it is empty.
export const CARD_DEFINITIONS: Record<string, Partial<Record<string, string>>> = {};
